# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestBandCampLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testBandCampLogin(self):
    self.driver.get("https://bandcamp.com/")
    self.driver.set_window_size(867, 1009)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username-field").click()
    self.driver.find_element(By.ID, "username-field").click()
    element = self.driver.find_element(By.ID, "username-field")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "username-field").click()
    self.driver.find_element(By.ID, "username-field").send_keys("charan04")
    self.driver.find_element(By.ID, "password-field").send_keys("9046@Charan")
    self.driver.find_element(By.CSS_SELECTOR, "button > div:nth-child(1)").click()
    # element = self.driver.find_element(By.CSS_SELECTOR, "button > div:nth-child(2)")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    # element = self.driver.find_element(By.CSS_SELECTOR, "button")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".no-image-placeholder").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"submenu-item-logout\"]").click()
    time.sleep(2)
    self.driver.close()